### ISSUE TITLE
Rechte benötigt

### ISSUE THREAD

**Issue by s6jastam** [NTW-Muenster/opal-mc-ml#5]
Hallo,

ich schreibe derzeit meine Masterarbeit zur Weiterentwicklung der Opal Machine Learning Masterclass. Im Rahmen dessen habe ich ein paar Veränderungen an den Sachen auf dem GitHub vorgenommen und würde diese gerne in einer neuen branch öffentlich zur Verfügung stellen, sodass wir die Sachen auf unsere Laptops laden können und in einer anstehenden Masterclass am 13.11 testen könnnen.
Ich bitte sie daher den github user s6jastam die nötigen Rechte zu erteilen um den branch pushen zu können.

Viele Grüße

**Comment by ntiltmann** [comment]
Hi, ich habe dich dem Team hinzugefügt. Jetzt müsstest du Branches erstellen können. Falls nicht, melde dich gerne nochmal

**Comment by s6jastam** [comment]
Hallo,

vielen Dank, dass das so schnell geklappt hat. Ich werde er gleich 
ausprobieren.

Viele Grüße,
Jannik Stammnitz
